# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1058, 787)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(260, 470, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(400, 470, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(740, 470, 75, 23))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify.setGeometry(QtCore.QRect(890, 470, 75, 23))
        self.btn_verify.setObjectName("btn_verify")
        self.btn_gen_keys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen_keys.setGeometry(QtCore.QRect(720, 80, 111, 23))
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 50, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txt_plain_text = QtWidgets.QLabel(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(120, 180, 51, 21))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.txt_cipher_text = QtWidgets.QLabel(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(120, 310, 61, 16))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.txt_plain_text_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plain_text_2.setGeometry(QtCore.QRect(210, 180, 311, 71))
        self.txt_plain_text_2.setObjectName("txt_plain_text_2")
        self.txt_cipher_text_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipher_text_2.setGeometry(QtCore.QRect(210, 310, 311, 71))
        self.txt_cipher_text_2.setObjectName("txt_cipher_text_2")
        self.txt_info_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_info_2.setGeometry(QtCore.QRect(680, 180, 321, 71))
        self.txt_info_2.setObjectName("txt_info_2")
        self.txt_sign_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_sign_2.setGeometry(QtCore.QRect(690, 320, 311, 71))
        self.txt_sign_2.setObjectName("txt_sign_2")
        self.txt_info = QtWidgets.QLabel(self.centralwidget)
        self.txt_info.setGeometry(QtCore.QRect(600, 180, 71, 16))
        self.txt_info.setObjectName("txt_info")
        self.txt_sign = QtWidgets.QLabel(self.centralwidget)
        self.txt_sign.setGeometry(QtCore.QRect(600, 310, 61, 20))
        self.txt_sign.setObjectName("txt_sign")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.btn_sign.setText(_translate("MainWindow", "Sign"))
        self.btn_verify.setText(_translate("MainWindow", "Verify"))
        self.btn_gen_keys.setText(_translate("MainWindow", "Generate Keys"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.txt_plain_text.setText(_translate("MainWindow", "Plain Text:"))
        self.txt_cipher_text.setText(_translate("MainWindow", "Cipher Text:"))
        self.txt_info.setText(_translate("MainWindow", "Information:"))
        self.txt_sign.setText(_translate("MainWindow", "Signature:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
